# Generated by Django 5.2.8 on 2026-01-20 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.AddField(
            model_name='workout',
            name='total_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', '-start_time'], name='workouts_wo_user_id_cccabd_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['weight'], name='workouts_wo_weight_69396c_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['one_rep_max'], name='workouts_wo_one_rep_9e779d_idx'),
        ),
    ]
