# Generated by Django 5.2.8 on 2026-01-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_options_workout_total_volume_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workoutset',
            name='workouts_wo_one_rep_9e779d_idx',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='one_rep_max',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='session_1rm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='session_volume',
            field=models.FloatField(default=0.0),
        ),
    ]
