# Generated by Django 5.2.8 on 2026-01-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0002_alter_workout_options_workout_total_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_rep_max', models.FloatField()),
                ('workout_exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_personal_record', to='workouts.workoutexercise')),
            ],
            options={
                'indexes': [models.Index(fields=['-one_rep_max'], name='stats_perso_one_rep_284f21_idx')],
            },
        ),
    ]
