# Generated by Django 5.2.8 on 2025-12-28 16:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('primary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('secondary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('tips', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('force', models.CharField(blank=True, choices=[('pull', 'Pull'), ('push', 'Push'), ('static', 'Static')], max_length=20, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('mechanic', models.CharField(blank=True, choices=[('compound', 'Compound'), ('isolation', 'Isolation')], max_length=20, null=True)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('stretching', 'Stretching'), ('plyometrics', 'Plyometrics'), ('strongman', 'Strongman'), ('powerlifting', 'Powerlifting'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting'), ('crossfit', 'Crossfit'), ('weighted bodyweight', 'Weighted Bodyweight'), ('assisted bodyweight', 'Assisted Bodyweight')], default='strength', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
