# Generated by Django 5.2.8 on 2026-01-30 01:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_old',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles_old',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles_old',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscles',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='exercises.equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.ManyToManyField(blank=True, related_name='primary_exercises', to='exercises.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.muscle'),
        ),
    ]
