# Generated by Django 5.2.8 on 2026-01-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_equipment_muscle_exercise_equipment_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment_old',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscles_old',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles_old',
        ),
    ]
